---

- name: create  tomcat_group
  group: name={{ tomcat_group }} state=present
  when: tomcat_group is defined
  tags:
    - tomcat8

- name: create tomcat_user
  user: name={{ tomcat_user }} createhome=no groups={{ tomcat_group }} append=yes
  when: tomcat_user is defined
  tags:
    - tomcat8
- stat: path="/tmp/{{apache_tomcat8_version}}.tar.gz"
  register: tomcat_tar_file
  tags:
    - tomcat8

- name: download tomcat {{tomcat8_download_url}}
  get_url: url="{{tomcat8_download_url}}" dest="/tmp" owner={{tomcat_user}} group={{tomcat_group}}
  when: tomcat_tar_file.stat.exists == False
  tags:
    - tomcat8

- name: mkdir log path
  file: path="{{log_path}}" owner="{{tomcat_user}}" group="{{tomcat_group}}" state=directory
  tags:
    - tomcat8

- name: install tomcat
  unarchive: src="/tmp/{{apache_tomcat8_version}}.tar.gz" dest="/usr/local/" creates=yes mode="go-w" owner={{tomcat_user}} group={{tomcat_group}}  copy=no
  tags:
    - tomcat8

- file: src="/usr/local/{{apache_tomcat8_version}}" dest="{{tomcat_home}}" owner={{tomcat_user}} group={{tomcat_group}} state=link
  become: true
  tags:
    - tomcat8

- name: remove ROOT app
  file:
    path: "{{tomcat_home}}/ROOT"
    state: absent
  become: true
  tags:
    - tomcat8


# - stat: path="{{tomcat_home}}"
#   register: tomcat_home_folder
#   tags:
#     - tomcat8
#
# - command: mv /usr/local/{{apache_tomcat8_version}} {{tomcat_home}}
#   when: tomcat_home_folder.stat.exists == False
#   tags:
#     - tomcat8

# - template: src="conf/server.xml" dest="{{tomcat_home}}/conf" owner={{tomcat_user}} group={{tomcat_group}}
#   tags:
#     - tomcat8
#
# - template: src="conf/logging.properties" dest="{{tomcat_home}}/conf" owner={{tomcat_user}} group={{tomcat_group}}
#   tags:
#     - tomcat8

##https
#- name: copy certificate_key
#  copy: src="server.crt" dest="{{tomcat_home}}/conf" owner={{tomcat_user}} group={{tomcat_group}} mode="777"
#
#- name: copy server.key.unsecure
#- copy: src="server.key.unsecure" dest="{{tomcat_home}}/conf" owner={{tomcat_user}} group={{tomcat_group}} mode="777"


- template: src="tomcat" dest="/etc/init.d/{{tomcat_service_name}}" owner={{tomcat_user}} group={{tomcat_group}}
  tags:
    - tomcat8

- file: dest="/etc/init.d/{{tomcat_service_name}}" state=touch mode="u=rx,g=rx,o=r" owner={{tomcat_user}} group={{tomcat_group}}
  tags:
    - tomcat8

- shell: "update-rc.d -f {{tomcat_service_name}} defaults"
  become: yes
  tags:
    - tomcat8
